[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', "dependencies"]
test = 'test'
optimizer_runs = 1000000
via-ir = true
evm_version = 'shanghai'
solc_version = '0.8.23'
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 140
bracket_spacing = true

[dependencies]
create2-helpers = "0.5.0"
