[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', "dependencies"]
test = 'test'
optimizer_runs = 1000000
via-ir = true
evm_version = 'cancun'
solc_version = '0.8.23'
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 140
bracket_spacing = true

[dependencies]
zeframlou-create3-factory = "567d6ec78cd0545f2fb18135dcb68298a5a1ef09"
