[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
optimizer_runs = 1000000
via-ir = true
evm_version = 'shanghai'
solc_version = '0.8.23'

[fmt]
line_length = 140
bracket_spacing = true
